jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://rm-bp125y2095k0z14ou5o.mysql.rds.aliyuncs.com:3306/vtapoco_staging?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowMultiQueries=true
jdbc.username=nhsoft_dev
jdbc.password=Wnb2qxxMWz93ZYKn4mwy